### ISSUE TITLE
New course format?

### ISSUE THREAD

**Issue by jmorenoamor** [dmotitsk/coursera#6]
I've enrolled to the "Computational Investing, Part I" course, and it has a different course layout than the rest of courses. so the downloader fails. Is this a new trend or only an exception?

https://class.coursera.org/compinvesting1-2012-001/class/index

Regards

**Comment by mkazin** [comment]
Hi jmorenoamor,

First, I'd like to preface this by stating I'm not part of the existing development team (I'm almost ready to submit my first patch), so don't take this as any sort of official answer, but only the opinion of a curious bystander. 

Having said that, I just looked into this particular question for you.  The "Computational Investing Part I" course page does look unusual, but it seems that underneath the visual differences it is based on the same structure common to all the other courses I have seen (see below for the technical details).

As far as I can tell from my (very limited) work with the source code, downloading content for the this class should work like any other, and it is actually working just fine\* for me.

Would you please provide more details about the nature of the failure you are experiencing, including answers to the following:
- What output do you get?   Are you using the -v option?  Do you get a stack trace?
- What is the exact command(s) you're using?
- Please verify you meet the requirements (Mechanize and BeautifulSoup both installed)
- Also would you verify you are using the most recent code (the subdomain patch tdjones fixed in August)?

Cheers!

-- mkazin

_*Note_: wiki and quiz pages don't seem to be supported and output a "couldn't download the file" message.  This isn't a failure, but possibly a yet be addressed feature or one ignored for whatever reason (my guess would be because quizzes are dynamic and generally uninteresting, and Wiki pages are ever-changing so downloading them may not be useful except for archival purposes).

**_Extra, technical detail for those interested:**_

After logging you in, the Coursera downloader then accesses the following URL:
    https://class.coursera.org/compinvesting1-2012-001/lecture/index

If you navigate to this address in your browser you will see the more familiar structure of multiple weeks of lectures.  This is what the downloader uses.

The relevant code is the assignment into 'lectures_url' (coursera.py lines 199-200).

**Comment by jmorenoamor** [comment]
Hi,

Thanks for the lecture index link, it gave me a new approach to the problem, because I thought this course had a special format and that was simply the cause of the problem.

I've put some more time to the problem to see what's going on, and managed to get a correct and incorrect execution, being the -t parameter the trigger of the problem:

#### Error

```
$ python coursera.py compinvesting1-2012-001 -p1 -v -ldebug
```

#### Success

```
$ python coursera.py compinvesting1-2012-001 -p1 -v -t movie -ldebug
```

So after looking a bit I got to this function:

```
def get_file_ext(self, url, content_type, res_type):
    m = REG_URL_FILE.search(url)
    if m:
        return m.group(2)
    m = REG_CONT_TYPE_EXT.match(content_type)
    if m:
        return m.group(1)
    return DEFAULT_EXT[res_type]
```

When the expected resource type is not inlcuded in the DEFAULT_EXT array, a KeyError exception is thrown. If we specify a resource type with -t, the program will look for that specific resource, and the problem will not reproduce.

One solution would be to add them to the array, but I prefered to write a more generic hotfix that warns of the problematic resource and keeps downloading the rest.

The two new resources I found were a Quiz and a Wiki page, so probably they wouldn't be downloaded anyway.

Thanks for your help @mkazin

Regards.

**Comment by mkazin** [comment]
Glad to be of help.

I'll have to double-check this, but I was sure I ran into that KeyError not on a wiki or quiz, but rather when it tried to process a PowerPoint file (.pptx) which didn't match the 'ppt' regex and went on to lookup in the dictionary.  I wasn't sure yet if that's because the dictionary contains only "ppt", or if there's something else I haven't seen, though it's possible I'm wrong and I simply wasn't paying close enough attention to my watch variables.

Thanks for the quick patch, @jmorenoamor, I'll take a look at it tomorrow when I'm fresh, and see if it also solves the problem I came to solve.

**Comment by jmorenoamor** [comment]
I think that would also trigger the KeyValue exception, but in that case it would be better to add pptx to the expeted extensions (under the ppt category) because it's a downloadable file.

I just added a branch in case the resource does not match anything expected, to drop a warning and continue instead of  crashing.

Glad to help, regards.

**Comment by dmotitsk** [comment]
Hello guys.

Thank you for your solutions of this problem. And especially for patches.
I will look at them today or tomorrow, as I'm currently very busy with my main work.
Thank you once again.

Regards,
Dmitry.
